### ISSUE TITLE
Sound stutter since commit "9a1df53"

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#1]
Hi, I tried the new build (2.0.0_Version2) but having the same problem.

**Comment by werwolf2303** [comment]
Ok can you upload a video of this with the cmd open

**Comment by lesar8** [comment]
Ok here it is: 
[Record.zip](https://github.com/SpotifyXP/SpotifyXP/files/12910300/Record.zip)

Looking at my recorded clip, I played the track "Angel" for around 1 minute. When the playback bar reached "01:14", I switch to the track "Kiss Them For Me" and sound beginning to stutter heavily, SpotifyXP hanging that is why I could not even click the red "Errors" dialog ..
Btw, the error message is "java.util.ConcurrentModificationException". Hope that helps.

**Comment by werwolf2303** [comment]
I think i found the problem. These requests shouldnt be made because all songs are already added to the list. Thats a bug i will try to fix it when I have time

**Comment by lesar8** [comment]
Hi! I grabbed the new build 1b7090e and the problem is still there.

**Comment by werwolf2303** [comment]
Can you give me a link to the playlist

**Comment by lesar8** [comment]
Sure, here is the link: spotify:playlist:7rTil6uINEa4kPcNn8Pax3

**Comment by werwolf2303** [comment]
thanks

**Comment by lesar8** [comment]
I just tried the commit 0d6df97 and 6a90f63, still no luck. I wonder if this happens to you as well?

**Comment by werwolf2303** [comment]
It doesnt happen on my side

**Comment by werwolf2303** [comment]
I have an idea. Install SpotifyXP on your main machine and check if it still happens

**Comment by werwolf2303** [comment]
Just an explanation of the code that fetches all tracks. It does a while loop and it gets the total tracks in the playlist and everytime a track is added it will check if the counter equals the total tracks and if it does the while loop ends. So i dont known whats wrong

**Comment by werwolf2303** [comment]
Can you install Windows XP on a vm and replicate this. Because then I can connect to it and debug the problem

**Comment by werwolf2303** [comment]
Click on the website on "See it in action" and then run code if it works you have access to the api

**Comment by lesar8** [comment]
The latest commit works fine. Thanks! Maybe one day we will found out the true root cause of this.
