### ISSUE TITLE
Stuck at creating API

### ISSUE THREAD

**Issue by Kenward79** [SpotifyXP/SpotifyXP#10]
Hi! I just installed SpotifyXP onto my machine running WinXP professional 2002 SP3. SpotifyXP keeps freezing right at Creating API, and then I get the message It looks like SpotifyXP is stuck. Do you want to close SpotifyXP?
![image](https://github.com/SpotifyXP/SpotifyXP/assets/45182774/1ce6e6b3-415b-4620-b81c-7a64db58c4fa)

**Comment by Kenward79** [comment]
I get an error that says 
Error: unable to access jarfile Spotify.jar
![image](https://github.com/SpotifyXP/SpotifyXP/assets/45182774/46b4007e-87bc-45ba-a057-a0e907403633)

**Comment by werwolf2303** [comment]
Execute this command in the folder where the SpotifyXP.jar is

**Comment by Kenward79** [comment]
It is located in documents and settings. How do I execute it in the folder?

**Comment by Kenward79** [comment]
![IMG_3194](https://github.com/SpotifyXP/SpotifyXP/assets/45182774/7d032ee5-5ea7-4378-907a-51235d94e2dd)
![IMG_3195](https://github.com/SpotifyXP/SpotifyXP/assets/45182774/23ddf667-7979-4fe7-9281-694f1af29e79)
![IMG_3196](https://github.com/SpotifyXP/SpotifyXP/assets/45182774/4cf96542-fbb9-4b05-bada-7ec6632b8f4d)
![IMG_3197](https://github.com/SpotifyXP/SpotifyXP/assets/45182774/730aa8c2-c162-4717-a17e-4efe6fe18095)

**Comment by werwolf2303** [comment]
Please install VLC 3.0.20 and try again
