### ISSUE TITLE
Crash with error "Can't find a suitable accesspoint" since commit 2c59761

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#11]
Hi, since commit 2c59761 SpotifyXp crashes with error "Can't find a suitable accesspoint" while listening to music. It happens randomly, but usually (just a feeling) after 10 minutes of play.
I suspect this change is the cause: **SpotifyXP now uses other ports**, because the error was mentioned in this part of codes:
`GraphicalMessage.sorryErrorExit("Can't find a suitable " + type);`

![crash](https://github.com/SpotifyXP/SpotifyXP/assets/133925958/735e8d74-102d-4085-b4d9-f4cfa1dff6d7)

**Comment by lesar8** [comment]
I suppose the latest build will have this error message "Can't find a suitable accesspoint" in the **Errors** dialog, instead of the showing the **Critical** message which crash the app as before. Unfortunately when this error occurs, the **Errors** does not open when I click on it. I still can see the counter number increase.

**Comment by werwolf2303** [comment]
I removed this error there is a possibility that I didn't upload this change to a nightly build

**Comment by werwolf2303** [comment]
I will upload the fix as soon as I am finished with a new feature
