### ISSUE TITLE
Stuck at "Creating CanvasPlayer..."

### ISSUE THREAD

**Issue by Minimewatson99** [SpotifyXP/SpotifyXP#12]
Using java -jar SpotifyXP.jar --setup-complete --debug tells me that it gets stuck here:

Module [INFO ] Skipping unknown command {cmd: 0x75, payload: 000000}

it then seems to timeout after a couple of minutes and then reconects to repeat the last couple of lines and then get stuck again.

Any fix?

**Comment by werwolf2303** [comment]
I cant help with these issues I use librespot-java to play spotify songs. Try to open an issue on that repo

**Comment by werwolf2303** [comment]
Please install VLC 3.0.20 and try again

**Comment by Minimewatson99** [comment]
Thanks, that fixed it.
