### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by 1Cross** [SpotifyXP/SpotifyXP#13]
Having to install Install Java 8 on the PC I'm restoring to working condition was already annoying but having "SpotifyXP appears to be stuck" message and get a blue screen of death right afterwards doesn't seem very fixable on my part.
No issues during install, Java 8 is completely operational, Windows XP is as updated as it can get, no anti-virus to mess with the jank.

For a little project its fine though! I appreciate the effort put into restoring XP to it's former state.

**Comment by 1Cross** [comment]
It happens right after Creating an API on a fresh install

**Comment by 1Cross** [comment]
![image](https://github.com/SpotifyXP/SpotifyXP/assets/77579779/4b687674-b1fc-4d1a-bea2-1f2f82e4ff50)
It happens in the span of a few miliseconds

**Comment by 1Cross** [comment]
![image](https://github.com/SpotifyXP/SpotifyXP/assets/77579779/60351426-65f4-4b58-a07f-8d0323ceb6f7)

**Comment by 1Cross** [comment]
Okay so since I caught the BSOD on camera, it's a issue on my end
it seems that the drivers I installed for the ancient wifi adapter are bad
https://www.dell.com/community/en/conversations/networking-internet-bluetooth/2200bg-wifi-drive-bsod-w22n51sys/647e4534f4ccf8a8de1484a0
probably some incompatibility between the 2200BG drivers and Java 8

**Comment by 1Cross** [comment]
Fixed! Just like the minimewatson I'm now stuck at Creating CanvasPlayer

**Comment by werwolf2303** [comment]
Please install VLC 3.0.20 and try again
