### ISSUE TITLE
No longer allows normal login after clicking Facebook login

### ISSUE THREAD

**Issue by StapleBacon5037** [SpotifyXP/SpotifyXP#15]
Clicking Facebook login and then not signing in with it causes the Facebook login page to open up by default next time Spotify xp is opened not allowing for the normal email login. This continues even after u installed and reinstalled

**Comment by StapleBacon5037** [comment]
This is what I get after running the debug tool if it helps at all
![untitled](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/d7637f51-a1bc-4a98-a77a-a97dd298b4ad)

**Comment by werwolf2303** [comment]
Address already in use. It looks like SpotifyXP is running in the backround. Can you make sure that its closed using the Taskmanager

**Comment by StapleBacon5037** [comment]
![crash](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/808f55e0-04a2-40a4-aa78-657d1f626bb6)
![crash-2](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/dc32e2e9-c310-4c01-88c4-df2d3e6f098f)
![crash-3](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/ab9f3a54-94fe-4876-a28e-8edfe4c2671f)
![crash-4](https://github.com/SpotifyXP/SpotifyXP/assets/76448863/40702c46-a228-4019-8edb-8313becfd1cc)

**Comment by werwolf2303** [comment]
I never tested this functionality it isn't even in the stable version of librespot-java. This code is in an untested unstable version. The 403 can mean anything and I can't do anything about it

**Comment by werwolf2303** [comment]
Can you reproduce this in my virtual machine?

**Comment by StapleBacon5037** [comment]
is there anything i can do to reset spotifyxp? ive tried reinstalling but it keeps trying to open in browser

**Comment by StapleBacon5037** [comment]
> Can you reproduce this in my virtual machine?

yeah, try signing in to spotifyxp and use facebook login instead. then dont sign in to facebook and instead close spotifyxp. then reopen it and try to sign in normally

**Comment by werwolf2303** [comment]
Can I give you login details and you do it on my virtual machine?

**Comment by StapleBacon5037** [comment]
> Can I give you login details and you do it on my virtual machine?

how would i do that for you? isnt it on your pc?

**Comment by werwolf2303** [comment]
You can connect remotely into it via realvnc

**Comment by StapleBacon5037** [comment]
alright, sure. should i send any files such as my vlc version and java version

**Comment by werwolf2303** [comment]
Yeah sure

**Comment by werwolf2303** [comment]
I am setting up the vm right now

**Comment by StapleBacon5037** [comment]
https://www.filepuma.com/download/java_development_kit_64bit_8.0.1510.12-16904/

this was the specific java download i used. its an offline download as the online ones werent working

**Comment by werwolf2303** [comment]
Unfortunately I only have time later because I have silvester dinner with my family

**Comment by StapleBacon5037** [comment]
alright, thats fine

**Comment by werwolf2303** [comment]
Please contact me per discord: werwolf2303

**Comment by werwolf2303** [comment]
I have decided to remove this functionality due to it not being in the stable branch of librespot-java and not working correctly
