### ISSUE TITLE
Stopping issue while playing

### ISSUE THREAD

**Issue by FlorianisonGitHub** [SpotifyXP/SpotifyXP#19]
I am enjoying myself playing music on Windows XP, but I get any issues with the playback, as it stops while playing any music.

Is this new Java project messy?

**Comment by werwolf2303** [comment]
What do you mean by "messy"

**Comment by FlorianisonGitHub** [comment]
> I am enjoying myself playing music on Windows XP, but I get any issues with the playback, as it stops while playing any music.
> 
> Is this new Java project messy?

And when I sometimes play another track when the player freezes, it doesn't do anything.

**Comment by werwolf2303** [comment]
Please run this in cmd where SpotifyXP.jar is located: "java -jar SpotifyXP.jar --setup-complete --debug". And please send me a video of this issue, you can record it with this: https://ia802803.us.archive.org/17/items/UnregisteredHyperCam2/HC2Setup.exe
