### ISSUE TITLE
Some problems with the latest commit

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#2]
Hi. I'm not sure if you already noticed it but on the latest commit, it's not possible to view artist's albums. This is the error message: [java.lang.IndexOutOfBoundsException: Index: *, Size: 0].
The Legacy theme is also broken, when play track it started to throw a lot of error messages:   [org.apache.batik.dom.util.SAXIOException content is not allowed in prolog] and [java.lang.NullPointerException]. This theme needs a redesign anyway, it looks just weird.

**Comment by werwolf2303** [comment]
I removed a lot of code for the compatibility for old themes. I am testing it when I have time

**Comment by werwolf2303** [comment]
I can view the artists albums

**Comment by werwolf2303** [comment]
I fixed the loading issue locally the only thing I must fix are the graphical bugs

**Comment by lesar8** [comment]
> I can view the artists albums

Hi, i recorded the clip for this. Basically i searched the keyword "Taylor, then access "Taylor Swift" profile page and her albums list and that trigger the problem.

[Problem.zip](https://github.com/SpotifyXP/SpotifyXP/files/13078650/Problem.zip)

**Comment by werwolf2303** [comment]
I did a refactoring of the code and forgot to add all the albums to the cache

**Comment by lesar8** [comment]
Thanks it fixed for me :-D

Would be so nice if you could re-organize the position of tabs in Legacy theme, it looks so good on old builds that released from months before.

![Legacy](https://github.com/SpotifyXP/SpotifyXP/assets/133925958/a1f37c9f-f763-4e26-a34a-1e0b4b2c6651)

**Comment by werwolf2303** [comment]
I tried to fix that and nothing worked but I hope now that the code for the old themes are removed this issue can be easily fixed

**Comment by lesar8** [comment]
I tried the latest commit and things now works as intended. Thank you!
