### ISSUE TITLE
I can't launch spotify after the completion of instalation.

### ISSUE THREAD

**Issue by Midnight-Rambler-72** [SpotifyXP/SpotifyXP#20]
When I finish the installation I can't find the way to open spotify.
![bez tytułu](https://github.com/SpotifyXP/SpotifyXP/assets/143538293/23cdea1d-a2e5-40c0-b849-fb75d8887d61)
It say "The application may be launched by selecting the installed icons." but I can't find a way to do it.
Btw I have installed required version of vlc and Java.

**Comment by werwolf2303** [comment]
There should be an icon on the desktop

**Comment by Midnight-Rambler-72** [comment]
Unfortunately There is not.

**Comment by werwolf2303** [comment]
Poease run this in cmd inside the folder were the SpotifyXP.jar is: "java -jar SpotifyXP.jar --debug". Plase send me the output of this

**Comment by Midnight-Rambler-72** [comment]
Still nothing
![1](https://github.com/SpotifyXP/SpotifyXP/assets/143538293/1e514f9a-9634-475d-a08b-f5bae4e2409c)
![2](https://github.com/SpotifyXP/SpotifyXP/assets/143538293/226377f8-428e-4bb4-af31-31472a34b56f)

**Comment by werwolf2303** [comment]
Try this build: https://github.com/SpotifyXP/SpotifyXP/actions/runs/7435131677/artifacts/1152091108

**Comment by Midnight-Rambler-72** [comment]
Thanks it worked! When I have first installed the Spotify it created an another folder called "desktop" located in my Documents and Settings folder, not in actuall desktop.
