### ISSUE TITLE
Double-clicking system tray icons no longer restores the window

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#22]
Thanks for the fix for #21 but there is another issue now, double-clicking SpotifyXp system tray icons no longer restores the window like old behavior. Need to right-click and choose "Open".

**Comment by werwolf2303** [comment]
Great that the fix worked. I will be looking into the double click thing when I have time

**Comment by werwolf2303** [comment]
I decided to remove the "Open" option it should behave normally again. I don't know if I uploaded the changes already but I promise I will do that when I am done with the Lyrics window
