### ISSUE TITLE
SpotifyXP failed to build player on windows xp professional sp3

### ISSUE THREAD

**Issue by ElenaorFoxQueen** [SpotifyXP/SpotifyXP#24]
Ooh hello. So for some reason I just cant lauch the app, it shows me this problem, please how do I fix it?
![image](https://github.com/SpotifyXP/SpotifyXP/assets/160389402/8a21aef4-8b36-4352-bae9-e734201d49fa)

**Comment by werwolf2303** [comment]
Which problem?

**Comment by werwolf2303** [comment]
Please open SpotifyXP with cmd "java -jar SpotifyXP.jar --setup-complete". Make sure this command is run inside the directory where the SpotifyXP.jar is located

**Comment by ElenaorFoxQueen** [comment]
> Please open SpotifyXP with cmd "java -jar SpotifyXP.jar --setup-complete". Make sure this command is run inside the directory where the SpotifyXP.jar is located

hmm lemme try that out. Thankyou so much

**Comment by ElenaorFoxQueen** [comment]
> Please open SpotifyXP with cmd "java -jar SpotifyXP.jar --setup-complete". Make sure this command is run inside the directory where the SpotifyXP.jar is located

oh well for some reason the same error appears :(

**Comment by werwolf2303** [comment]
Please post the output of the cmd window as a screenshot. I forgot please execute this command "java -jar SpotifyXP.jar --setup-complete --debug". I am going to play resident evil now so it can be that I don't respond immediately

**Comment by ElenaorFoxQueen** [comment]
oops sorry I forgot about this :(
Well uhh Idk how to do that cause I'm a complete noob and uhh I kinda give up :(

**Comment by werwolf2303** [comment]
Press the Windows key + R. Type cmd or cmd.exe in the Run command box. Then type "cd FOLDERWHERESPOTIFYXPFIlEIS". Then type the command from before. Please send me a screenshot of the cmd window afterwards
