### ISSUE TITLE
Disable volume normalization

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#29]
Hi, while reading the debug log for fun, I noticed the line:
```
[DEBUG::Module ] Loaded normalization data, track_gain: -7.471917, track_peak: 1
.0167016, album_gain: -7.471917, album_peak: 1.0167016
```
I am curious whether it is possible to disable volume normalization on SpotifyXP, similar to the feature that is found in Spotify app itself?

**Comment by werwolf2303** [comment]
I will look into that

**Comment by lesar8** [comment]
Thanks for the new release! This has some very interesting settings that I don't understand what they do:
> Preload enabled
> Mixer search keywords
> Release line delay

I would like your advice on how these settings works? Thank you.

**Comment by werwolf2303** [comment]
Honestly I don't know maybe you can get more information here: https://github.com/librespot-org/librespot-java/. This library is the heart of SpotifyXP
