### ISSUE TITLE
Stuck on 'Creating API'

### ISSUE THREAD

**Issue by rm199x** [SpotifyXP/SpotifyXP#3]
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Bar>cd C:\Documents and Settings\Bar\SpotifyXP\

C:\Documents and Settings\Bar\SpotifyXP>java -jar SpotifyXP.jar --setup-complete
--debug
Found setup argument => true
SpotifyXP [INFO ] Loaded Theme => DarkGreen from => Werwolf2303
Module [INFO ] Loaded aps into pool: {accesspoint=[ap-gew4.spotify.com:4070, ap-
gew4.spotify.com:443, ap-gew4.spotify.com:80, ap-gew1.spotify.com:4070, ap-gue1.
spotify.com:443, ap-guc3.spotify.com:80], dealer=[gew4-dealer.spotify.com:443, g
ew1-dealer.spotify.com:443, gue1-dealer.spotify.com:443, guc3-dealer.spotify.com
:443], spclient=[gew4-spclient.spotify.com:443, gew1-spclient.spotify.com:443, g
ue1-spclient.spotify.com:443, guc3-spclient.spotify.com:443]}
Module [INFO ] Created new session! {deviceId: fc74d539854fd66a5c1c700cb42b7c631
368a688, ap: ap-gew4.spotify.com:4070, proxy: false}
Module [INFO ] Connected successfully!
Module [DEBUG ] Session.Receiver started
Module:0 [INFO ] There are {} cached entries.
Module [DEBUG ] AsyncProcessor{dealer-worker} has started} has started
Module [DEBUG ] AsyncProcessor{event-service-sender} has started} has started
Module [INFO ] Skipping SecretBlock
Module [INFO ] Received LicenseVersion: 0
Module [INFO ] Received CountryCode: NL
Module [DEBUG ] Token expired or not suitable, requesting again. {scopes: [playl
ist-read], oldToken: null}}
Module [DEBUG ] Send Mercury request, seq: 1, uri: hm://keymaster/token/authenti
cated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=f
c74d539854fd66a5c1c700cb42b7c631368a688, method: GET
Module [DEBUG ] Parsed product info: {audiobook-onboarding-completed=0, remote-c
ontrol=6, publish-activity=0, audio-preview-url-template=https://p.scdn.co/mp3-p
review/{id}, incognito_mode_timeout=21600, ad-formats-preroll-video=0, type=prem
ium, ab_recently_played_feature_time_filter_threshold=com.spotify.gaia=30,drivin
g-mode=120,spotify%3Ainternal%3Astartpage=30, license-agreements=, publish-playl
ist=1, buffering-strategy=0, expiry=1, ab-desktop-hide-follow=0, ab-collection-h
ide-unavailable-albums=0, capper-profile=, payments-initial-campaign=default, pr
ofile-image-upload=1, enable-annotations=2, ab-ad-player-targeting=1, subscripti
on-enddate=, india-experience=0, video-wifi-initial-bitrate=800000, ab-mobile-ru
nning-onlymanualmode=only-manual, playlist-annotations-markup=0, prefetch-keys=1
, allow-override-internal-prefs=0, prefetch-window-max=2, send-email=1, ad-forma
ts-video-takeover=1, ab-collection-bookmark-model=1, pause-after=0, local-files-
import=0, video-manifest-url=[https://spclient.wg.spotify.com/manifests/v6/{type}](https://spclient.wg.spotify.com/manifests/v6/%7Btype%7D)
/sources/{source_id}/options/supports_drm, ab-sugarpills-sanity-check=2, playlis
t-folders=1, arsenal_country=1, track-cap=0, audiobook-onboarding-dismissed=0, a
b-mobile-running-tempo-detection=Control, is_email_verified=0, shows-collection=
1, enable-annotations-read=0, addon-hifi=0, mobile-browse=0, payments-locked-sta
te=0, employee-free-opt-in=0, shows-collection-jam=0, ab-browse-music-tuesday=1,
offline=1, streaming=1, fb-info-confirmation=control, audio-quality=1, wanted-l
icenses=, lastfm-session=, ab-desktop-playlist-annotation-edit=1, ab-mobile-disc
over=0, widevine-license-url=https://spclient.wg.spotify.com/widevine-license/v1
/video/license, key-caching-max-count=10000, hifi-eligible=0, ad-session-persist
ence=1, video-initial-bitrate=200000, ab-play-history=0, mobile-payment=0, payme
nt-state=, key-caching-max-offline-seconds=1800, ugc-abuse-report-url=https://su/
pport.spotify.com/abuse/?uri={uri}, shuffle-algorithm=1, use-pl3=0, image-url=ht
tps://i.scdn.co/image/{file_id}, use-playlist-app=0, enable-autostart=1, metadat
a-link-lookup-modes=0, shuffle=0, instant-search=0, instant-search-expand-sideba
r=0, use-playlist-uris=0, user-profile-show-invitation-codes=0, ab-ad-requester=
1, nft-disabled=1, ab-collection-union=1, key-memory-cache-mode=1:15,300, libspo
tify=1, high-bitrate=1, head-file-caching=1, radio=1, key-caching-auto-offline=0
, explicit-content=1, video-cdn-sampling=1, ab-android-push-notifications=1, unr
estricted=1, use-fb-publish-backend=2, client-deprecated=1, app-developer=0, buf
fering-strategy-parameters=0.8:0.2:0.0:0.0:0.0:0.0:1.0:10:10:2000:10000:10485760
, enable-gapless=1, ab-playlist-extender=5, enable-crossfade=1, ad-persist-rewar
d-time=0, public-toplist=1, network-operator-premium-activation=1, video-device-
blacklisted=0, collection=1, fb-grant-permission-local-render=0, backend-advised
-bitrate=1, autoplay=1, catalogue=premium, storage-size-config=10240,90,500,3, a
ds=0, head-files-url=[https://heads-ak-spotify-com.akamaized.net/head/{file_id}](https://heads-ak-spotify-com.akamaized.net/head/%7Bfile_id%7D),
ab-collection-followed-artists-only=0, browse-overview-enabled=1, on-demand=1, a
p-resolve-pods=1, name=Spotify Premium, sidebar-navigation-enabled=0, loudness-l
evels=1:-5.0,0.0,3.0:-2.0, mobile-login=1, product-expiry=, hifi-optin-intent=0,
preferred-locale=en, license-acceptance-grace-days=30, prefetch-strategy=18, ug
c-abuse-report=1, ab-watch-now=0, financial-product=pr:premium,tc:0,rt:v2_NL_def
ault_full-price-premium-1m_10.99_EUR_default, ab-collection-offline-mode=0, stre
aming-rules=, head-files=1, capping-bar-threshold=3601, ab-new-share-flow=0, vid
eo-keyframe-url=[http://keyframes-fa.cdn.spotify.com/keyframes/v1/sources/{source](http://keyframes-fa.cdn.spotify.com/keyframes/v1/sources/%7Bsource)
_id}/keyframe/heights/{height}/timestamps/{timestamp_ms}.jpg, mobile=1, is_maybe
_in_social_session=0, ab-mobile-startpage=0, ab-moments-experience=0, ab-mobile-
social-feed=1, ab-test-group=972, player-license=premium}
Module [INFO ] Skipping UnknownData_AllZeros
Module [INFO ] Skipping LegacyWelcome
Module [DEBUG ] Handling packet, cmd: MercuryEvent, seq: -7928582745939247104, f
lags: 1, parts: 1
Module [DEBUG ] Couldn't dispatch Mercury event {seq: -7928582745939247104, uri:
hm://pusher/v1/connections/ZmM3NGQ1Mzk4NTRmZDY2YTVjMWM3MDBjYjQyYjdjNjMxMzY4YTY4
OCtBUCt0Y3A6Ly9nZXc0LWFjY2Vzc3BvaW50LWMta3dyZy5nZXc0LnNwb3RpZnkubmV0OjUwMTArQzM1
Rjk4NTZFMzdGOUFFOERBQzA3QUNDRUU4NzYzRUE0NzdCMzk1Q0ZGQUUzM0I2MDY5RTNERTVCNjFBQjc1
Mw%3D%3D, code: 200, payload: []}
Module [DEBUG ] Received 0x10: FE0759E5639EC638FB7180C1FAE484FE2C78A982
Module [DEBUG ] Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
Module [DEBUG ] Updated token successfully! {scopes: [playlist-read], newToken:
StoredToken{expiresIn=3600, accessToken='BQBKbZ...ukNfsY', scopes=[playlist-read
], timestamp=1698172936845}}}
Module [INFO ] Authenticated as repainer!
Module [INFO ] Skipping unknown command {cmd: 0x75, payload: 000000}
Module [DEBUG ] Dealer connected! {host: guc3-dealer.spotify.com}}
Module [DEBUG ] Couldn't dispatch message: hm://pusher/v1/connections/ZmM3NGQ1Mz
k4NTRmZDY2YTVjMWM3MDBjYjQyYjdjNjMxMzY4YTY4OCtkZWFsZXIrdGNwOi8vZ3VjMy1kZWFsZXItYS
0zejMwLmd1YzMuc3BvdGlmeS5uZXQ6NTcwMCs2Rjc4MERBNzYyOEJGNDEwQ0EyMzFENDg0QTQxOTdGRD
EwNjdFMTFFNjhFRDQ1MkUzQkQ3M0IwOTM4MTk5M0FF
Module [DEBUG ] AsyncProcessor{put-state-worker} has started} has started

**Comment by werwolf2303** [comment]
If this issue still persists. Please retest it on Windows 10 or 11

**Comment by werwolf2303** [comment]
or Windows 7, 8, 8.1
