### ISSUE TITLE
PanicState in PlayerListener

### ISSUE THREAD

**Issue by Aswedishproto** [SpotifyXP/SpotifyXP#30]
I had just installed this, i had installed the newest one (2.0.2), it was working fine for a few, but then all of a sudden it stopped working, i got the error [java.lang.UnknownError: PanicState in PlayerListener], I uninstalled SpotifyXP, it did not work, i deleted it and installed 2.0.0 and it did not work at all either. 

![image](https://github.com/SpotifyXP/SpotifyXP/assets/155917415/8f948a33-0c01-4ef3-aa9a-b639cc494668)

I also reinstalled java, it did nothing to effect the issue

**Comment by werwolf2303** [comment]
Does it happen immediately?

**Comment by Aswedishproto** [comment]
Not imminently, I got to use it for about 10 minuets then it started doing that. Last night i reinstalled it and after accidentally breaking my headphones I discovered if I boot my computer with them plugged in the sound driver breaks. After restarting it, it does in fact work(ish). It works for a while, but every now and then I get the same error still, and have to restart the software.

**Comment by werwolf2303** [comment]
Ok that also happens for me. My techno got also very abruptly interrupted😂 I will fix that if I can

**Comment by Aswedishproto** [comment]
Alright
