### ISSUE TITLE
The shortcut does not appear after finishing the installation.

### ISSUE THREAD

**Issue by HIXOXIH** [SpotifyXP/SpotifyXP#36]
I downloaded and installed java 8 501. VLC Media Player version 3.0.20. Both 32bit. I double clicked on SpotifyXP.jar. I went to the last installation screen. I clicked "Finish" The screen disappears, and nothing else happens after that. There is no icon created on the desktop. What is wrong? I need help.

**Comment by werwolf2303** [comment]
Sorry for the late response, I've been busy. I've created a new nightly build that improves error handling in the setup and it would now be the question if the setup now says that something has failed. Please try the new nightly build

**Comment by HIXOXIH** [comment]
Okay. I will try this. Thank U. 😉

**Comment by HIXOXIH** [comment]
Hello. I did what you asked. I downloaded the version you said. But this,
after I double click to run the installer, absolutely nothing happens. Name
appears the installation steps. Help.

Em ter, 28 de mai de 2024 10:33, werwolf2303 ***@***.***>
escreveu:

**Comment by HIXOXIH** [comment]
Correcting the error in my writing: NAME = NOT

Em qui, 30 de mai de 2024 13:07, HAVOC HVC ***@***.***> escreveu:

**Comment by HIXOXIH** [comment]
But there is nothing to show. Just nothing happen after i double click the SpotifyXP.jar!

**Comment by HIXOXIH** [comment]
Thank you very much. I'll be waiting for your response :)

**Comment by Jri-creator** [comment]
After you double-click the file, SpotifyXP.jar, it doesn't do anything? What Operating System [OS] are you using?

**Comment by HIXOXIH** [comment]
The installation screen appears. I continue until I reach the point where I click on "Finish". But after that, nothing else happens. No icon appears on the desktop. I use Windows XP Professional with SP3.

**Comment by werwolf2303** [comment]
Please run SpotifyXP with this command in the directory where the SpotifyXP jar exists: "java -jar SpotifyXP.jar --debug --setup-complete" and then please upload a screenshot or something. Open CMD with windows+r and then type cd [DIRECTORY_PATH]

**Comment by HIXOXIH** [comment]
I'll try this.

**Comment by HIXOXIH** [comment]
WOW!!!! I DO THAT!! AND NOW ITS WORKING :))))))) THANK YOU!!!

**Comment by HIXOXIH** [comment]
I tried exactly as you said but it wasn't going. So I used a trick that I know to do these commands by creating a shortcut of what I want to execute.

**Comment by HIXOXIH** [comment]
I noticed that the sound is a little low. But other than that it's ok!

**Comment by Jri-creator** [comment]
I believe that, unlike my Linux, Windows doesn't understand how to create the taskbar/deskbar button contain the --setup-complete flag. [Not sure why it's doing this now, as it hasn't done this with previous versions of SpotifyXP]

**Comment by werwolf2303** [comment]
I ported this to Java 8. This is the code that creates the Shortcut: https://github.com/BlackOverlord666/mslinks

**Comment by Jri-creator** [comment]
@werwolf2303 This issue can be closed, unless issue arises again.
