### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Delwari** [SpotifyXP/SpotifyXP#37]
Hello everything is fine? I have this problem, could you help me?

Windows: Vista Professional Home
VLC: 3.0.20 x32
JAVA: 8u152 (I believe it is x32, I don't know how to check)

ERROR:
![WhatsApp Image 2024-05-31 at 6 20 59 PM](https://github.com/SpotifyXP/SpotifyXP/assets/119232181/80b20f57-0367-4ace-b33e-d93d10cd7197)
![WhatsApp Image 2024-05-31 at 6 21 08 PM](https://github.com/SpotifyXP/SpotifyXP/assets/119232181/f7f1e5de-488a-470b-8a04-fc7b970a7d91)

**Comment by Jri-creator** [comment]
Hello, sorry for the late response. How long have you had SpotifyXP on your computer?

**Comment by Jri-creator** [comment]
@werwolf2303 This Issue has been open, but with no response, for a while. Do you want to close this?

**Comment by werwolf2303** [comment]
This one is a network issue. UnknownHpstException means it can't find the spotify servers
