### ISSUE TITLE
Functional scrollbar at homepage

### ISSUE THREAD

**Issue by iansquenet** [SpotifyXP/SpotifyXP#38]
I'm having trouble scrolling down to check podcast episodes tailored towards me.
The only way I could do right now is by scrolling at the "Episodes for you" space.
![image](https://github.com/SpotifyXP/SpotifyXP/assets/36297463/eb60dc63-6772-4f00-bc2a-90e297bf9973)

**Comment by Jri-creator** [comment]
Sorry for the late response. The owner of SpotifyXP, @werwolf2303 , is fixing some UI issues, I believe. What Operating System are you using SpotifyXP on?

**Comment by iansquenet** [comment]
> Sorry for the late response. The owner of SpotifyXP, @werwolf2303 , is fixing some UI issues, I believe. What Operating System are you using SpotifyXP on?

Windows 10 Pro version 22H2.

**Comment by werwolf2303** [comment]
If you download the newest nightly you can resize the window to make the scrollbar appear

**Comment by werwolf2303** [comment]
And I saw the problem with different screens just now

![Screenshot_2024-06-07_15-59-45](https://github.com/SpotifyXP/SpotifyXP/assets/66752411/8eb71585-b9e1-4750-9d84-1e4dd97d8b3f)
fricking tiny

**Comment by Jri-creator** [comment]
@werwolf2303 This issue can be closed.
