### ISSUE TITLE
Crashes at startup since commit 4e1b794

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#39]
Hi, SpotifyXP crashes at startup since commit 4e1b794. I'm running WinXP with Java 8 build 242 installed.

![Crashes](https://github.com/SpotifyXP/SpotifyXP/assets/133925958/f8473936-d8fb-43fe-8798-c5976e34f9c0)

**Comment by Jri-creator** [comment]
I'm having an issue, too! I'm my case, the build won't install.

Terminal Output:
` java -jar SpotifyXP.jar
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.swing.JLabel.setText(String)" because "this.linfo" is null
	at com.spotifyxp.panels.SplashPanel.show(SplashPanel.java:21)
	at com.spotifyxp.Initiator.initSplashPanel(Initiator.java:109)
	at com.spotifyxp.Initiator.main(Initiator.java:67)
`

**Comment by werwolf2303** [comment]
I rebuild this part of the ui. It seems like that this component isn't initialized before it is called

**Comment by werwolf2303** [comment]
![Screenshot_2024-06-10_16-54-08](https://github.com/SpotifyXP/SpotifyXP/assets/66752411/60757dd3-8091-4693-9c95-12dcf82e09c8)

Works for me

**Comment by Jri-creator** [comment]
Same, using `java -jar SpotifyXP.jar`, but it's not working.

**Comment by Gonimbrasia** [comment]
Still the same with b7567af

**Comment by werwolf2303** [comment]
This commit was only for a problem that prevented installing SpotifyXP on linux

**Comment by Jri-creator** [comment]
@werwolf2303  We can close this issue, as it now launches. Different error is happening in a new issue.
