### ISSUE TITLE
A couple of problems on the latest build

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#4]
Hi, i could not access the "Hot List" results as whenever i click on it, an error will occur: [java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: 2]

Another annoying problem is that track sometimes stops playing after 20 to 25 seconds into the song, here is an error messages:
[java.lang.Throwable: Failed requesting chunk from network, index: *]
[java.util.concurrent.RejectedExecutionException: Task com.spotifyxp.deps.xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$Internal... rejected...] (Damn, it's long and i could not able to copy the log..)

Finally, the "Playback History" list should be sort from newest to oldest for more convenience, just my 2 cents.

**Comment by werwolf2303** [comment]
Ok I will fix these issues and change the PlaybackHistory.

**Comment by werwolf2303** [comment]
I have to do something for school and I have a depressive episode right now so it can take a while

**Comment by lesar8** [comment]
Ah it's Fine I understand.

**Comment by werwolf2303** [comment]
So implemented the playback history thing. I needed to partially learn SQL for this. Now to the "playback stops after x seconds". Can you make a video of this with cmd open and these arguments "--setup-complete --debug".

**Comment by lesar8** [comment]
Hi, here is the clip.
[Recorded.zip](https://github.com/SpotifyXP/SpotifyXP/files/13327712/Recorded.zip)

The track "Comfort Zone - Main Menu" (from Sonic Mania album) stopped at 00:23.

**Comment by werwolf2303** [comment]
Is it always the same song?

**Comment by werwolf2303** [comment]
It looks like that your internet is the problem. Can you try using a mobile hotspot?

**Comment by lesar8** [comment]
> Is it always the same song?

No, it happens randomly.

> It looks like that your internet is the problem. Can you try using a mobile hotspot?

It's not the case here i think. I use 4G phone's Internet (connect my phone to PC via USB) and the same problem happens.

**Comment by werwolf2303** [comment]
Ok I dont know this doesnt happen on my side. I can spin up a virtual machine and you can try it on my end if you want.

**Comment by lesar8** [comment]
Well, I tested some previous build and found out that the "Menu Bar" problem appears since commit 04a131c.

Later i will make a regression tests for the "Playback" problem. I remember the older build behave better.

**Comment by werwolf2303** [comment]
So I think you mean that the menubar doesnt work. When yes then I fixed it in the latest nightly version

**Comment by lesar8** [comment]
> So I think you mean that the menubar doesnt work. When yes then I fixed it in the latest nightly version

 I can confirm it's fixed, thanks!

**Comment by lesar8** [comment]
I have found an oddity, right-click on the SpotifyXp icon in the system tray and choose "Exit" does not actually exit the app, but instead minimize the window. I'd more prefer to exit the application here.

**Comment by werwolf2303** [comment]
Ok thanks for pointing that out. I will fix that

**Comment by werwolf2303** [comment]
I am installing Windows XP on and arm64 laptop right now so it can take a while before I can test that

**Comment by lesar8** [comment]
Phew.. After a long and painful test, I finally found the culprit of the "Playback" problem where songs stop playing after a few seconds. 
The problem appears since commit a24ee02. My assumption was that it had something to do with the change in these 3 files: Player.java, PlayerSession.java and PlayerUtils.java.

Also, I managed to copy the full line of error code:
`[java.util.concurrent.RejectedExecutionException: Task com.spotifyxp.deps.xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream$$Lambda$119/11978004@1610e36 rejected from java.util.concurrent.ThreadPoolExecutor@779164[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 13]] `

**Comment by werwolf2303** [comment]
But why does this not happen on my side?

**Comment by lesar8** [comment]
Well, clearly a difficult question to answer. I wonder if the difference in OS service pack numbers or Java version between my PC and yours is the cause? I am running XP SP2 Professional and Java 8 Update 241.

Regardless of whatever it is, I propose to simply revert the change and release the test build, then we will try it out. If somehow it works fine for both of us then let's call it a happy ending.

**Comment by werwolf2303** [comment]
I am running SpotifyXP on an arm64 mac with MacOS Sonoma

**Comment by werwolf2303** [comment]
I will change the code and send you a build. You must wait a couple of hours because I will be in School soon

**Comment by werwolf2303** [comment]
Try this one:  http://werwolf2303.de/SpotifyXP.jar

**Comment by lesar8** [comment]
At the moment your build seems to works pretty well on my side, all songs played smoothly. Big thanks :-)

BTW, i noticed that the Playback History dialog is not opening. Here is an error message:
[java.lang.Throwable: Can't establish a connection to the playback history database]

**Comment by werwolf2303** [comment]
Ok I will look into that error
