### ISSUE TITLE
Install doesnt work.

### ISSUE THREAD

**Issue by Blackmaster117** [SpotifyXP/SpotifyXP#40]
After install the only thing in the install folder are the extensions folder, the icon and the installer.

**Comment by Jri-creator** [comment]
Can you post a picture for better understanding?

Also, what OS are you using?

**Comment by Blackmaster117** [comment]
Windows XP 32bit

It's literally just a folder with the three listed things the extensions folder is empty

**Comment by Blackmaster117** [comment]
SP3

**Comment by emperortrademark999** [comment]
having this exact same issue on Windows XP x64 SP2, the folder has the JAR installer, the ico file and the extensions folder with nothing inside the folder. found a fix?

**Comment by Blackmaster117** [comment]
Nope still broken.

**Comment by emperortrademark999** [comment]
i think https://github.com/SpotifyXP/SpotifyXP/issues/36 might be similar to this issue, @Blackmaster117 try using the solution in there

**Comment by Jri-creator** [comment]
@werwolf2303 This issue can be closed.
