### ISSUE TITLE
[Theme] SpotifyXP installer pane/picture refresh 

### ISSUE THREAD

**Issue by Jri-creator** [SpotifyXP/SpotifyXP#42]
I have created a SpotifyXP installer pane, because I was bored and I thought this may help improve the theme of the SpotifyXP installer.
Not saying that your current SpotifyXP installer pane is bad, I just wanted to create a (potentially) better installer pane that you may use without my credit.

Final(?) Pane:
![2024_06_16_0yv_Kleki](https://github.com/SpotifyXP/SpotifyXP/assets/145695642/f05bda4b-cd07-4a7f-9438-720922fd135f)
Various revisions for your use:  {.Zip file}
[Images.zip](https://github.com/user-attachments/files/15860442/Images.zip)

If you think this is better, let me know and use the images.

If not, no worries! I was just bored, and I like graphic designing.

No credit is needed at ALL, but if you want to credit, I would appreciate it.

**Comment by Jri-creator** [comment]
Video of me testing the images:

https://github.com/SpotifyXP/SpotifyXP/assets/145695642/06d44442-1917-402c-9b85-d7542a547c07

Sorry for the audio delay. Didn't notice the mic mess-up when I edited it in Audacity and bonded the audio.

**Comment by werwolf2303** [comment]
Thank you 😁. This will be in the next commit

**Comment by Jri-creator** [comment]
Glad I could help with designs!

**Comment by werwolf2303** [comment]
What is this test.jar?

**Comment by Jri-creator** [comment]
Just a test to ensure the picture worked in the setup utility. Nothing else.

The test build was based on the latest public release of SpotifyXP.

I had extracted the Jar file, replaced the setup.png with the one I made, then used JarBuild to rebuild the Jar for testing. 

Note that I deleted the test jars after I recorded the video. I can't upload the test jar due to it's size.

**Comment by werwolf2303** [comment]
Can you make the background of the final version transparent? I think that would look nice

**Comment by Jri-creator** [comment]
Let me see what I could do...

Here:
![2024_06_22_0wm_Kleki](https://github.com/SpotifyXP/SpotifyXP/assets/145695642/a231341b-bf87-4aae-9a2f-8e7b01b37078)
