### ISSUE TITLE
Can't login in Spotify account

### ISSUE THREAD

**Issue by oleg-dubinskiy** [SpotifyXP/SpotifyXP#43]
The app does no longer crash since recent commits, but now it's not possible to login with any Spotify account (neither Free, nor Premium). The splash simply hangs at "Checking login" screen and nothing happens after that. In stable 2.0.2 branch, the login form immediately appears as it should, but in latest master it does not. I tried as to install it first, same without doing that (with a `--setup-complete` option), but unfortunately it does not fix the problem.
Tested on the following platforms:
Linux (Ubuntu 21.10) amd64 + OpenJDK 18-ea amd64,
ReactOS 0.4.15-dev-8058-ga7cbb60 i386 + OpenJDK 8u42 i386.
Windows XP Professional SP3 i386 + Java 8u51 i386.
![Linux](https://github.com/SpotifyXP/SpotifyXP/assets/26385117/5daaa19d-e925-4001-8a09-198e9f179b1b)
![ROS](https://github.com/SpotifyXP/SpotifyXP/assets/26385117/bc4a8a33-7349-46eb-9fd5-219758b3a6c2)
![XP](https://github.com/SpotifyXP/SpotifyXP/assets/26385117/15791f87-5ae9-4cdb-8f1e-fc661471912f)
So this is definitely a bug in SpotifyXP itself.
No any visible debug output in the terminal however.
If any additional debugging (enabling a special debug option) is required, please specify it to me, I'll capture a log and will attach it here. Thanks. :slightly_smiling_face:

**Comment by Jri-creator** [comment]
Confirmed issue with latest commits.

Same issue reported, found under 98th and 99th commit.

**Comment by Jri-creator** [comment]
@oleg-dubinskiy Attach --setup-complete and --debug to the command, then copy/paste the output in a text file.

My output, from Ubuntu 24.04:
[debug.txt](https://github.com/user-attachments/files/16114875/debug.txt)

**Comment by oleg-dubinskiy** [comment]
> @oleg-dubinskiy Attach --setup-complete and --debug to the command, then copy/paste the output in a text file.
> 
> My output, from Ubuntu 24.04: [debug.txt](https://github.com/user-attachments/files/16114875/debug.txt)

Done. Here are 3 logs from all the OSes tested above:
[debug_Ubuntu_21.10.txt](https://github.com/user-attachments/files/16115233/debug_Ubuntu_21.10.txt)
[debug_ReactOS_0.4.15_dev.txt](https://github.com/user-attachments/files/16115239/debug_ReactOS_0.4.15_dev.txt)
[debug_Windows_XP_Pro_SP3.txt](https://github.com/user-attachments/files/16115241/debug_Windows_XP_Pro_SP3.txt)

All 3 logs look almost same, however there are some small differences. But the source of problem seems identical in all 3 testcases.

**Comment by Jri-creator** [comment]
@werwolf2303   Looks like it's hanging on some internal process. 

`[THROWABLE java.awt.IllegalComponentStateException] contentPane cannot be set to null.
[THROWABLE java.awt.IllegalComponentStateException] java.desktop/javax.swing.JRootPane.setContentPane(JRootPane.java:591)
[THROWABLE java.awt.IllegalComponentStateException] java.desktop/javax.swing.JDialog.setContentPane(JDialog.java:1036)
**[THROWABLE java.awt.IllegalComponentStateException] com.spotifyxp.dialogs.LoginDialog.<init>(LoginDialog.java:30)
[THROWABLE java.awt.IllegalComponentStateException] com.spotifyxp.Initiator.checkLogin(Initiator.java:276)
[THROWABLE java.awt.IllegalComponentStateException] com.spotifyxp.Initiator.main(Initiator.java:89)
java.awt.IllegalComponentStateException: contentPane cannot be set to null.
	at java.desktop/javax.swing.JRootPane.setContentPane(JRootPane.java:591)
	at java.desktop/javax.swing.JDialog.setContentPane(JDialog.java:1036)
	at com.spotifyxp.dialogs.LoginDialog.<init>(LoginDialog.java:30)
	at com.spotifyxp.Initiator.checkLogin(Initiator.java:276)
	at com.spotifyxp.Initiator.main(Initiator.java:89)**
`

And what's in bold is what triggering the bug in the beta build(s).

**Comment by Jri-creator** [comment]
@werwolf2303 That, unfortunately, didn't work. The issue is still occuring, and the debug log looks the same.

 `java -jar SpotifyXP.jar --setup-complete --debug
[INFO ] Found setup argument => true
[WARNING ] Key 'settings.ui.theme' has an invalid value: 'DARKGREEN'! Resetting to default value...
[WARNING ] Unknown Theme: 'DARKGREEN'! Trying to load theme differently
[INFO ] Loaded Theme => DarkGreen from => Werwolf2303
[THROWABLE java.lang.NullPointerException] Cannot invoke "com.spotifyxp.swingextension.CustomLengthTextField.setColumns(int)" because "this.spotifyusernamefield" is null
[THROWABLE java.lang.NullPointerException] com.spotifyxp.dialogs.LoginDialog.<init>(LoginDialog.java:31)
[THROWABLE java.lang.NullPointerException] com.spotifyxp.Initiator.checkLogin(Initiator.java:276)
[THROWABLE java.lang.NullPointerException] com.spotifyxp.Initiator.main(Initiator.java:89)
java.lang.NullPointerException: Cannot invoke "com.spotifyxp.swingextension.CustomLengthTextField.setColumns(int)" because "this.spotifyusernamefield" is null
	at com.spotifyxp.dialogs.LoginDialog.<init>(LoginDialog.java:31)
	at com.spotifyxp.Initiator.checkLogin(Initiator.java:276)
	at com.spotifyxp.Initiator.main(Initiator.java:89)`

**Comment by werwolf2303** [comment]
Ok I will look into that

**Comment by werwolf2303** [comment]
Ok I will look into that

**Comment by Jri-creator** [comment]
@werwolf2303  Looks like error starts here: `[THROWABLE java.lang.NullPointerException] Cannot invoke "com.spotifyxp.swingextension.CustomLengthTextField.setColumns(int)" because "this.spotifyusernamefield" is null [THROWABLE java.lang.NullPointerException] com.spotifyxp.dialogs.LoginDialog.<init>(LoginDialog.java:31) [THROWABLE java.lang.NullPointerException] com.spotifyxp.Initiator.checkLogin(Initiator.java:276) [THROWABLE java.lang.NullPointerException] com.spotifyxp.Initiator.main(Initiator.java:89) java.lang.NullPointerException: Cannot invoke "com.spotifyxp.swingextension.CustomLengthTextField.setColumns(int)" because "this.spotifyusernamefield" is null at com.spotifyxp.dialogs.LoginDialog.<init>(LoginDialog.java:31) at com.spotifyxp.Initiator.checkLogin(Initiator.java:276) at com.spotifyxp.Initiator.main(Initiator.java:89)`

Something about `this.spotifyusernamefield` being `null` is what's causing the java throw [java error]

**Comment by Jri-creator** [comment]
And according to my research and ChatGPT, The error points to line 31 in the LoginDialog constructor, and that spotifyusernamefield must be initialized before line 31.

ChatGPT's words:

"The java.lang.NullPointerException you're encountering indicates that the spotifyusernamefield object is null when you attempt to call the setColumns(int) method on it. This means the object has not been properly initialized before its method is invoked. Let's go through steps to identify and fix this issue.

**Steps to Fix the NullPointerException**

1. Check Initialization of spotifyusernamefield:

Ensure that spotifyusernamefield is properly initialized before you call any methods on it.

2. Review the Constructor in LoginDialog:

The error points to line 31 in the LoginDialog constructor. Verify that spotifyusernamefield is initialized before line 31.

3. Verify Object Creation and Assignment:

Confirm that spotifyusernamefield is assigned a new instance of CustomLengthTextField or retrieved from somewhere before calling setColumns." [Note: AI is not always correct. Check for mistakes]

I'll spare you the rest, as this info should help.

**Comment by werwolf2303** [comment]
![Screenshot_2024-07-07_17-28-00](https://github.com/SpotifyXP/SpotifyXP/assets/66752411/9f2f840e-261f-48ba-b690-984b3a01ecb2)
It works for me.... Weird

**Comment by werwolf2303** [comment]
https://www.file-upload.net/download-15356766/SpotifyXP.jar.html

**Comment by werwolf2303** [comment]
Please try this one

**Comment by Jri-creator** [comment]
Ok, that is weird. Maybe Github isn't building it correctly?

Anyways, with further progress, a different error is shown: 
![Screenshot from 2024-07-07 11-48-48](https://github.com/SpotifyXP/SpotifyXP/assets/145695642/d830051e-fe9b-4fb9-82b4-7c3695e22fdf)

![Screenshot from 2024-07-07 11-49-01](https://github.com/SpotifyXP/SpotifyXP/assets/145695642/f3e9ba37-4790-4c93-a6e4-4789b8f6c834)

**Comment by Jri-creator** [comment]
Debug:

[debug.txt](https://github.com/user-attachments/files/16119885/debug.txt)

**Comment by werwolf2303** [comment]
I can't fix the reconnecting thing. That depends on your network

**Comment by Jri-creator** [comment]
I've rebooted both my computer and network, and this issue still persists. The public release [Ver 2.0.2] works as intended, so I am not sure if this is a network issue.

**Comment by oleg-dubinskiy** [comment]
> Please try this one

Just tried, thanks! It works for me now too (at least in ReactOS 0.4.15-dev)! :smiley: 
![spotifyxp-fixed](https://github.com/SpotifyXP/SpotifyXP/assets/26385117/240456da-88b4-494a-9400-300d20ad27e6)

**Comment by oleg-dubinskiy** [comment]
> Ok, that is weird. Maybe Github isn't building it correctly?
> 
> Anyways, with further progress, a different error is shown: ![Screenshot from 2024-07-07 11-48-48](https://private-user-images.githubusercontent.com/145695642/346347198-d830051e-fe9b-4fb9-82b4-7c3695e22fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzM3MzEsIm5iZiI6MTcyMDM3MzQzMSwicGF0aCI6Ii8xNDU2OTU2NDIvMzQ2MzQ3MTk4LWQ4MzAwNTFlLWZlOWItNGZiOS04MmI0LTdjMzY5NWUyMmZkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNzMwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGIwOTk0MGE4MTgyYmUyMDVkMmE2MTM4MjcxMzUwMTZhMzcwODM4ZjI5ZTk5YjdlZjM1ZjJkMjE5YzA2MDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.helI2yHYDibSTpCmsCeXQpIj6HYMx-VkT6T6kbu1sgk)
> 
> ![Screenshot from 2024-07-07 11-49-01](https://private-user-images.githubusercontent.com/145695642/346347206-f3e9ba37-4790-4c93-a6e4-4789b8f6c834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzM3MzEsIm5iZiI6MTcyMDM3MzQzMSwicGF0aCI6Ii8xNDU2OTU2NDIvMzQ2MzQ3MjA2LWYzZTliYTM3LTQ3OTAtNGM5My1hNmU0LTQ3ODliOGY2YzgzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNzMwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTM2ZTA3MGY1ODU0OTEwODk0MDhlZjI3Y2U0MDMxMWVmNzI1MTUzMTcyZmJkNzc5OGY5ZWEyODg2MGI1YmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m_Q3QLKAgC7OWB5E6QhdL2wPky_iEWcsMSlgFqyT9DU)

This error occurs for me too, but **only after login, at "Creating API..." step**.

**Comment by oleg-dubinskiy** [comment]
Here's a new debug log I got from Command Prompt: 
[debug_ReactOS_0.4.15_dev_NEW.txt](https://github.com/user-attachments/files/16120186/debug_ReactOS_0.4.15_dev_NEW.txt)

**Comment by Jri-creator** [comment]
@werwolf2303 Is it misconfigured Spotify API requests? The PUBLIC beta (2.0.2) creates files essential for connections to the Spotify API. IDK, it's your code.

**Comment by werwolf2303** [comment]
I also don't know I have to compare the code

**Comment by Jri-creator** [comment]
@werwolf2303 @oleg-dubinskiy  Just to experiment, I tried to swap the SpotifyXP file from the Public Beta to the 100th commit beta in the SpotifyXP folder, and it didn't work.
