### ISSUE TITLE
Exception with endless reconnecting after login

### ISSUE THREAD

**Issue by oleg-dubinskiy** [SpotifyXP/SpotifyXP#44]
After login into Spotify account, or with already logined one, when SpotifyXP tries to connect, appears EOFException/SocketTimeoutExcetion (actually only 2nd one), followed by endless looped reconnecting. And no actual connecting and login into my account.
The debug output is as follows:
```
[WARNING ] Key 'settings.ui.theme' has an invalid value: 'DARKGREEN'! Resetting
to default value...
[WARNING ] Unknown Theme: 'DARKGREEN'! Trying to load theme differently
[INFO ] Loaded Theme => DarkGreen from => Werwolf2303
[INFO::Module ] Loaded aps into pool: {accesspoint=[ap-gew4.spotify.com:4070, ap
-gew4.spotify.com:443, ap-gew4.spotify.com:80, ap-guc3.spotify.com:4070, ap-gue1
.spotify.com:443, ap-gew1.spotify.com:80], dealer=[gew4-dealer.spotify.com:443,
guc3-dealer.spotify.com:443, gue1-dealer.spotify.com:443, gew1-dealer.spotify.co
m:443], spclient=[gew4-spclient.spotify.com:443, guc3-spclient.spotify.com:443,
gue1-spclient.spotify.com:443, gew1-spclient.spotify.com:443]}
[INFO::Module ] Created new session! {deviceId: da08e14022cf2ea1f23019b25696c23d
623a6390, ap: ap-gew1.spotify.com:80, proxy: false}
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[WARNING ] Init of player failed! Retrying... (1)
[INFO::Module ] Loaded aps into pool: {accesspoint=[ap-gew4.spotify.com:4070, ap
-gew4.spotify.com:443, ap-gew4.spotify.com:80, ap-guc3.spotify.com:4070, ap-gew1
.spotify.com:443, ap-gae2.spotify.com:80], dealer=[gew4-dealer.spotify.com:443,
guc3-dealer.spotify.com:443, gew1-dealer.spotify.com:443, gae2-dealer.spotify.co
m:443], spclient=[gew4-spclient.spotify.com:443, guc3-spclient.spotify.com:443,
gew1-spclient.spotify.com:443, gae2-spclient.spotify.com:443]}
[INFO::Module ] Created new session! {deviceId: d745b0fcefc2d9de2f95b017c4285d74
2c492a4b, ap: ap-gew4.spotify.com:4070, proxy: false}
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
[INFO::Module ] Exception! Trying other ap...
```
(tested on ReactOS 0.4.15-dev, but is also the same on all other OSes).
[debug_ReactOS_0.4.15_dev_NEW.txt](https://github.com/user-attachments/files/16316376/debug_ReactOS_0.4.15_dev_NEW.txt)
Tested with this Java version: https://archive.org/details/jre1.8.0_251_XP, and there is exactly the same result.
It occurs starting from f6c1b7ca828df5adbe85f2fec328045909a43787, which had a purpose to fix a LoginDialog crash, but did not fix it actually. It has introduced this issue instead.
**I already figured out how to fix it and made a fix in my branch, so will submit a new PR soon.**

**Comment by werwolf2303** [comment]
This reconnecting thing was an attempt to make spotifyxp more stable. When SpotifyXP reconnects and has an error it retries and retries and retries.... but eventually it should die with a message popping up

**Comment by oleg-dubinskiy** [comment]
> This reconnecting thing was an attempt to make spotifyxp more stable. When SpotifyXP reconnects and has an error it retries and retries and retries.... but eventually it should die with a message popping up

But more interesting is the reason: why it reconnects even when there's actually no error? Maybe it's a problem of the client itself instead of a server? Other clients are connecting fine. Maybe it reconnects in case when it shouldn't? Spotify server actually doesn't fail. It seems to me that exception is simply always triggered, even when no any connection error has occurred.
Is my linked fix correct btw? It ignores that exception when there's no any error yet and SpotifyXP connects and works just fine after my changes. :slightly_smiling_face:

**Comment by werwolf2303** [comment]
I check for an error via try catch. So it guaranteed that an exception happened but I don't know why. This also happened at my old school's wifi

**Comment by oleg-dubinskiy** [comment]
Still not fixed in latest master for me. The same exception is still occurring.
Perhaps we need to ignore that still.
