### ISSUE TITLE
problem installing spotifyxp.

### ISSUE THREAD

**Issue by Nicholas-ERROR** [SpotifyXP/SpotifyXP#47]

**Comment by Nicholas-ERROR** [comment]
okay. im a bit new to commenting.
anyway. im having problems with installing spotifyxp on my pentium 4. ive tried a fair few versions. i managed to get it running a few times by installing 1.9 then 2.0. but it never installed fully. always had problems

**Comment by Nicholas-ERROR** [comment]
heres the output, note im using 2.0 to get this debug

[java.nio.file.InvalidPathException: Illegal char <:> at index 4: /SpotifyXP/SpotifyXP.jar] sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
sun.nio.fs.WindowsPathParser.parse(Unknown Source)
sun.nio.fs.WindowsPathParser.parse(Unknown Source)
sun.nio.fs.WindowsPath.parse(Unknown Source)
sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
java.nio.file.Paths.get(Unknown Source)
com.spotifyxp.deps.mslinks.ShellLinkHelper.setLocalTarget(ShellLinkHelper.java:143)
com.spotifyxp.deps.mslinks.ShellLinkHelper.setLocalTarget(ShellLinkHelper.java:108)
com.spotifyxp.setup.Setup$Content.beginInstallWindows(Setup.java:254)
com.spotifyxp.setup.Setup$Content.beginInstall(Setup.java:280)
com.spotifyxp.setup.Setup$Content.showFileInfo(Setup.java:141)
com.spotifyxp.setup.Setup$Content.switchToNext(Setup.java:293)
com.spotifyxp.setup.Setup$Content$3.actionPerformed(Setup.java:115)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

**Comment by werwolf2303** [comment]
What is your language and what is your username? 
Have you tried a nighlty build under the actions tab?

I am asking because it seems like java has a problem parsing the path where the .jar file is copied.

**Comment by Nicholas-ERROR** [comment]
sorry for taking so long. its English and i dont know where to get the nighlty build from really. my username on the machine is Nicholas. i took out the dir for safety reasons. if you need the specs i can get them for you

**Comment by werwolf2303** [comment]
Can you give me the full directory path? If you don't want to upload it to GitHub you can contact me on discord via my username: werwolf2303

**Comment by Nicholas-ERROR** [comment]
for the directory. and this is just side info. theres 2 hard drives. 2 cdroms and a floppy drive in the machine. 6 partitions by the hard drives. note theres 5 os's on the machine. the actual directory is... oh i just noted. its going for the C directory then trys the I directory. the C is for windows 98 plus. I is for the windows xp home which im trying to install it on. anyway. the directory is this. "C:\I:\Documents and Settings\Nicholas/SpotifyXP/SpotifyXP.jar"

**Comment by werwolf2303** [comment]
There's the problem. The path is invalid... this is such a small percentage of users that have such a configuration that it's not worth fixing. But after my vacation I will implement a command line argument that will store everything in ram

**Comment by Nicholas-ERROR** [comment]
okay thanks. though a idea. maybe on one of the screens for installing you allow the user to give the program a spot to install it on? i feel this could fix the problem. you dont have to. thanks overall though for the help!

**Comment by Nicholas-ERROR** [comment]
oh and a quick note. ive tried 2.02 as well. but it doesnt seem to make any icons. it just makes the program things but doesnt run it or so. no real way for me to run it again. and it doesnt say any errors. nor debuging data.

**Comment by werwolf2303** [comment]
!!!This project is DEAD!!! For updates: https://github.com/SpotifyXP/SpotifyXP/issues/51. I will leave the repository open for someone to fix it
