### ISSUE TITLE
Off-by-one bug in search results.

### ISSUE THREAD

**Issue by MTlabs** [SpotifyXP/SpotifyXP#48]
There is off-by-one bug in search results that happens when the "Load more" item is there.

Example _(see image)_:
If i select the first real result there "Nightwish", it will load the second one "Tarja" instead. All the other items are also shifted by one. This also means that the first real item can't be selected at all, since it will always load the next one. The search works fine when the "Load more" item is not there.
![screeen](https://github.com/user-attachments/assets/f11a4310-ad5f-432f-ad3b-655abcbc3efc)

**Comment by Jri-creator** [comment]
Hello.

Sorry for the late reply. Did you try the latest Unreleased Beta, and see if that resolves this issue?

You may find it here, as of August 11, 2024:

https://github.com/SpotifyXP/SpotifyXP/actions/runs/10303415420

**Comment by MTlabs** [comment]
I can't replicate the bug on the release you provided, since the "Load more" button doesn't show anymore for me. So i guess the bug was fixed or something changed. It works perfectly now. Sorry for not testing on the lastest version in the first place.
