### ISSUE TITLE
Settings screen has broken height and width on KDE Plasma

### ISSUE THREAD

**Issue by rcky844** [SpotifyXP/SpotifyXP#49]
![image](https://github.com/user-attachments/assets/8daf23e6-3411-4c3b-b714-17ff8ab1e31a)

I guess the image can speak for itself.
Side note, I can still temporarily use Settings if I maximized the window, so it would be a critical bug but a **workaround** exists.
Anotherr workaround appears to be invoking the same option again.

**Comment by rcky844** [comment]
More notes:
All window except the main one seem to be broken, with incorrect initial width and height, and Settings cannot be resized (maybe due to the design itself)

**Comment by werwolf2303** [comment]
I can't fix it because login is no longer possible. I will reopen this when it's possible again

**Comment by werwolf2303** [comment]
Does it still happen in the newest nightly build

**Comment by werwolf2303** [comment]
Please run the jar in a terminal with: "java -jar SpotifyXP.jar --setup-complete --debug"

**Comment by werwolf2303** [comment]
Closed due to inactitivy
