### ISSUE TITLE
Installer window is too small

### ISSUE THREAD

**Issue by emv33** [SpotifyXP/SpotifyXP#5]
On Windows 11 installer window is too small and there is no scrollbar to scroll through the licence text.

![image](https://github.com/SpotifyXP/SpotifyXP/assets/142946271/5867bf7d-596e-47ea-b020-9659f44f051d)

![image](https://github.com/SpotifyXP/SpotifyXP/assets/142946271/b6c7a3e0-ad63-442d-b828-26cced51d5fc)

**Comment by werwolf2303** [comment]
This is weird

**Comment by werwolf2303** [comment]
![Uploading Image 15.11.23 at 15.26.png…]()

**Comment by werwolf2303** [comment]
![Image 15 11 23 at 15 26](https://github.com/SpotifyXP/SpotifyXP/assets/66752411/398b1e3d-4364-445f-a7ca-069b64596dea)
