### ISSUE TITLE
READ THE README! Spotify is the reason why...

### ISSUE THREAD

**Issue by Jri-creator** [SpotifyXP/SpotifyXP#51]
Welp, that's very bad for many projects that use this Spotify API.

Sorry that Spotify closed the old Username/Password API. Maybe Spotify really doesn't want either unofficial clients or older computers to connect to Spotify Servers. 

That may have been caused due to the increased popularity of either This Project, or an increase in other projects.

I know it's going to ruffle some developers feathers, so to speak, and they are going to complain. I was starting to develop something, but now I'm going to have to throw it away.

Let's keep hope. While it may not be usable anymore, either there will be a breakthrough, or another dev will hold the reins, so to speak.

Thanks for creating this project. Without this, me and various others would be left without Spotify, and would be forced to either upgrade or get a new computer. I hope that you can find something that helps bring this project alive, even if it means a major rewrite in code, which I know is annoying, but there are users relying on you.

Let's hope for a breakthrough...

**Comment by WalterKnox** [comment]
Yeah, this sucks. I have never used Spotify before, just found this program 6 days ago and was very much enjoying playing music on my old Dell Inspiron 1000 (and many other low powered XP machines.) I created a Spotify accound just for this. I guess I can go ahead and delete it now.

**Comment by werwolf2303** [comment]
There are other login options but that would mean extra steps log in. I will investigate

**Comment by werwolf2303** [comment]
I'm using a reverse engineered internal api client and spotify doesn't use username and password log in. Instead they are using there website to get some sort of key that can log you in. And the authentication by key I think still works. I have 2 options now:

1. Make the user open a browser and type in a very long url by hand

2. Integrate a browser inside the login window (per JavaFX 8.. I don't know if the browser used is new enough to support that kind of javascript)

**Comment by Jri-creator** [comment]
You can ask the user to copy/paste the link into their browser, or have the link clickable and ask the user for their MyPal or other default browser.

**Comment by werwolf2303** [comment]
Oh you're right. I totally missed that

**Comment by Jri-creator** [comment]
I know that there was something in settings for a version of SpotifyXP that asked about that, but that could only be set by Windows Owners. Linux owners couldn't set the Browser, even if they could, due to how it's set up. I'm guessing that Java 8 can't determine the default browser, it requires a user to set it?

Maybe both "Launch in MyPal" and "Copy/Paste Link" options should be available.

**Comment by StapleBacon5037** [comment]
That is unfortunate

**Comment by Midnight-Rambler-72** [comment]
Damn, that project was very promising! It's kinda sad, really.

**Comment by Jri-creator** [comment]
I'm very sorry to hear about this. I understand the anger you are going through, the fact that Spotify made a wrongful decision to close this API. I'm going to contact a few people I know, but I don't know if anyone will help. For Me, I don't have the knowledge, yet. After all, I'm just 14 (when writing this post). Hope to work again with you again, soon...

**Comment by DA-TENSHI** [comment]
It's been a while since I opened this repository and I just noticed it.
I'm really sorry to hear that.
I hope a new solution can be found as soon as possible.
(I use translation because I cannot handle English well. I am a Japanese speaker.)
