### ISSUE TITLE
New Login method does not work: the app is restricted to Spotify Premium only

### ISSUE THREAD

**Issue by oleg-dubinskiy** [SpotifyXP/SpotifyXP#55]
When I'm trying to Login via the new Login method, starting SpotifyXP and then an official Spotify app, then open Devices section and clicking SpotifyXP app, it does now work as described: there is an error that this app is restricted only to Spotify Premium subscription and after clicking the item, nothing happens:
![изображение](https://github.com/user-attachments/assets/649bbd1b-e70f-44c0-8384-ba1979602175)
Debug output is visible on screenshot too.
Tested OS: Ubuntu 21.10.
I don't know how to see the version of the official Spotify app in the modern interface (if needed).

**Comment by oleg-dubinskiy** [comment]
My current subscription is Spotify is Free if what.

**Comment by Jri-creator** [comment]
I can confirm that this issue is happening with my Free Spotify, also.

**Comment by Jri-creator** [comment]
OS: Ubuntu 24.04 LTS
Spotify apps tried: Mobile Spotify, Ubuntu Desktop, MacOS Ventura Desktop, Windows 11 Desktop.
Current Subscription: Spotify Free

**Comment by werwolf2303** [comment]
Unfortunately I can't do anything about that until  Spotify publishes this part in their documentation.... or until somebody can extract the commercial Spotify library

**Comment by lesar8** [comment]
I'm on Free plan and can confirm this issue. I wonder if it is possible to change the Device ID from "SpotifyXP" to "Chromecast"? Spotify allow Free account connect to any Chromecast devices (such as Android TV), maybe this trick will actually work..?

![Chromecast](https://github.com/user-attachments/assets/f6bcdf0d-19e5-4826-b804-bbd3f0426f57)

**Comment by Jri-creator** [comment]
If the program broadcasts itself as a Chromecast and uses those protocols, but I am not sure if that would work.

**Comment by werwolf2303** [comment]
Spotify also allows Spotify Connect devices for free accounts. What I would need is the Spotify eSDK. If one of you have a device that supports Spotify Connect with a free account and the update files have a filesystem I could extract the eSDK from it
