### ISSUE TITLE
Add an option to disable caching

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#57]
Hi, the "cache" folder is getting too big. To save some space on my old hdd, i wonder if you can add an option to disable caching? I don't mind if it make the song slower to stream. Thank you.

**Comment by werwolf2303** [comment]
I will look into that

**Comment by Jri-creator** [comment]
Maybe instead of disabling cache, which would impact performance, have an option for the app to clear the cache before exit. The app may take a little longer to close, but would be better.

**Comment by werwolf2303** [comment]
Consider this implement
