### ISSUE TITLE
Add option to disable auto queue songs

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#58]
Hi, for a long time I had faced this problem, if I play songs in my "Playlist", music starts to lag/stutter heavily and CPU usage constantly hitting 30% ~ 40%. This problem does NOT happens when i play songs in "Hot List" or search results.

I doubt the reason is because my playlist is too big (over 2000 songs), SpotifyXP keep queuing up my playlist and this process is very SLOW and hitting the CPU hard. Hence, I suggest that implementing this feature may resolve the problem.

**Comment by werwolf2303** [comment]
Good idea.... over 2000 songs???? 

I think that the problem is that I fetch all songs of the playlist instead of doing it like 20 songs at a time until scrolled like in the library tab. 

I will implement a fix for this and implement the "Disable auto queue" setting.

I can't say when because I'm coding in my rust project right now

**Comment by lesar8** [comment]
Thanks it works but for some reason, changing the setting from the GUI does not remember the change. I need to open "config.json" and modify the line "user.settings.autoqueue.disabled" to "true.
![abc](https://github.com/user-attachments/assets/f3f79f0b-cc3f-40f9-8c3f-26941ae5045d)

Moreover, "Disable Spotify Connect" and "Disable Caching" settings can be change from the GUI and it actually DOES remember the change.

**Comment by werwolf2303** [comment]
Oh. I totally forgot to add this code

**Comment by werwolf2303** [comment]
[69c2c8e](https://github.com/SpotifyXP/SpotifyXP/commit/69c2c8e3a0f39c43b8e896a2b5fdb74621791dd7)
 ·

**Comment by lesar8** [comment]
Fixed for me, thanks.
