### ISSUE TITLE
Keeps Saying My Login Is Invalid

### ISSUE THREAD

**Issue by theanthonydavenport** [SpotifyXP/SpotifyXP#62]
<img width="348" alt="Screenshot 2024-11-21 at 20 37 37" src="https://github.com/user-attachments/assets/36e9b315-84cd-4f7b-b392-485e5b88e837">

<img width="318" alt="Screenshot 2024-11-21 at 20 40 14" src="https://github.com/user-attachments/assets/d18aa6a1-622b-4551-9b81-1b75e1da537b">

**Comment by werwolf2303** [comment]
This is an old version. Spotify removed the ability to log in via username and password. Please download a nightly build

**Comment by theanthonydavenport** [comment]
At a fear of sounding stupid, can you link it?

**Comment by werwolf2303** [comment]
https://github.com/SpotifyXP/SpotifyXP/actions/runs/11822549758

**Comment by theanthonydavenport** [comment]
That just does this.
<img width="596" alt="Screenshot 2024-11-22 at 14 22 17" src="https://github.com/user-attachments/assets/36b88cf8-cc76-49ae-b880-abffb69269c1">

**Comment by werwolf2303** [comment]
This is the installer

**Comment by werwolf2303** [comment]
This gets executed if "--setup-complete" is not given as parameter. The shortcut on the desktop gives SpotifyXP that parameter

**Comment by theanthonydavenport** [comment]
Done that, after figuring out which button is accept on the Parallels XP VM, but it isn't showing up in Spotify.

<img width="1366" alt="Screenshot 2024-11-22 at 14 26 15" src="https://github.com/user-attachments/assets/e71f4066-6287-4d16-9e03-054e379172e7">
<img width="340" alt="Screenshot 2024-11-22 at 14 26 31" src="https://github.com/user-attachments/assets/b8935806-922d-4520-9933-6c207212d82f">

**Comment by werwolf2303** [comment]
Should be showing in devices? Hmm, weird another one of these cases.

**Comment by theanthonydavenport** [comment]
Trying in macOS works after a restart of SpotifyXP on Sequoia, but the Parallels XP VM isn't getting control.

**Comment by werwolf2303** [comment]
If you authenticated in macOS, copy the credentials.json in home/SpotifyXP to the same path in the vm

**Comment by theanthonydavenport** [comment]
Are you able to help via a Discord screenshare or something?

**Comment by werwolf2303** [comment]
Sure, why not.

My username is the same one as here on github

**Comment by theanthonydavenport** [comment]
Added.
