### ISSUE TITLE
Cannot Install Spotifyxp.jar

### ISSUE THREAD

**Issue by HighwayEleven** [SpotifyXP/SpotifyXP#64]
when i tried to download the spotifyxp.jar i couldn't find it anywhere, the releases tab only gives me full opensource zip

**Comment by werwolf2303** [comment]
Because I don't have a roadmap or anything, I build the jar as soon as I changed something in the code. You can find them here: https://github.com/SpotifyXP/SpotifyXP/actions/workflows/main.yaml
