### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by gamesfunclub** [SpotifyXP/SpotifyXP#65]
Hello today i downloaded SpotifyXP but when i try to login i put the correct email and password but it says its wrong i even tried another accounts but get the same problems

**Comment by Jri-creator** [comment]
You must be using the SpotifyXP version from the Release Builds, which is currently out of date. Please use the SpotifyXP from the latest Actions. Goto the Actions tab of this Repository, and download the latest version.
________________________________
From: gamesfunclub ***@***.***>
Sent: Thursday, December 5, 2024 4:44 PM
To: SpotifyXP/SpotifyXP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SpotifyXP/SpotifyXP] Cant log in (Issue #65)


Hello today i downloaded SpotifyXP but when i try to login i put the correct email and password but it says its wrong i even tried another accounts but get the same problems

**Comment by Jri-creator** [comment]
@werwolf2303 Can you remove the Releases, or turn one of the Actions builds into a Release?

**Comment by Jri-creator** [comment]
I just made a README edit to inform new users. Would it work?

**Comment by Jri-creator** [comment]
It's in pull requests.

**Comment by Jri-creator** [comment]
@werwolf2303 ?

**Comment by Jri-creator** [comment]
-@werwolf2303 Can we close this issue?
