### ISSUE TITLE
Suggestion to improve performance

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#7]
Hi, so my playlist has over 1,500 songs and when i play it, SpotifyXP tend to fetch and save the URIs of all the songs from my playlist to the file called "play.state". This file took quite some time to load at startup (mine took 5 - 6 seconds), to the point where I simply delete it to speed up the loading times! Now, imagine if someone had their playlist with several thousand songs...

I have an idea to implement some sort of algorithm for SpotifyXP, so when fetching and saving the URIs for queueing, it will be limited to 50 -> 100 songs. I means, no one listens to thousands of songs in one session.

Besides that, I noticed the error "[java.lang.RuntimeException: java.sql.SQLException: query does not return ResultSet]" is still happens when "Remove all" is clicked on Playback History dialog. And I hope you can add a right-click "Copy" feature for "Errors" dialog.

**Comment by werwolf2303** [comment]
Ok I will implement the suggestion and fix the issue.

**Comment by lesar8** [comment]
Hi, i've tested and here's the result:

- The new queue algorithm works great so far.
- Click "Remove all" will clear the history, but the SQLite database also stop working until re-start SpotifyXP. Here is an errors:
[java.lang.Throwable: Can't establish a connection to the playback history database] 
[java.sql.SQLException: path to '..\SpotifyXP\playbackhistory.dbjdbc:sqlite:..\SpotifyXP\playbackhistory.db': '..\SpotifyXP\playbackhistory.dbjdbc:sqlite:C:' does not exist] 
- The Copy feature for "Errors" dialog has not implemented yet, i can use Ctrl-C as a workaround.

**Comment by werwolf2303** [comment]
Ok I will fix these issues

**Comment by lesar8** [comment]
Seems like it doesn't work on my side. When I right-click on the dialog, only the 'Remove' option appears.

**Comment by werwolf2303** [comment]
Ok I understood your idea wrong

**Comment by lesar8** [comment]
I wonder why the context menu only appears if right-click on the grey area, but rather not when right-click directly the log line.. Maybe we could improve the logic here.

**Comment by lesar8** [comment]
Hi, I tried the latest build and the context menu only shows "Remove" (by clicking on the grey area). I can probably live with "Ctrl+C" method but not sure why it's so hard to implement "Copy" option?
![1](https://github.com/SpotifyXP/SpotifyXP/assets/133925958/5ffd4e4c-0266-4f0c-b9ec-bb22d8c5ae4f)

**Comment by werwolf2303** [comment]
Ok I will also implement a copy option in the exception selection screen

**Comment by werwolf2303** [comment]
The context menu works by registering a listener to an object in the JFrame for example an JPanel and when the JPanel detectects a right click on itself it opens the context menu. But when an object is inside the JPanel the right click doesn't get carried to the JPanel

**Comment by lesar8** [comment]
Thanks for your analysis. Consider the limits of JPanel, i'm guessing the best way might be add a "Copy" option above "Remove" option, so the newcomer can easily figure out how to copy a log line. The Ctrl-C key may be a little bit tricky to found.

**Comment by werwolf2303** [comment]
I will see how I implement that. I am at school right now so please wait a little bit

**Comment by lesar8** [comment]
Hi, latest build tested. The "Copy" feature does not work stably, it copied some random log lines and not what appears on the dialog. Example:

```
[java.lang.ArrayIndexOutOfBoundsException: -1] java.util.ArrayList.elementData(ArrayList.java:422)
java.util.ArrayList.get(ArrayList.java:435)
com.spotifyxp.panels.ContentPanel$22.lambda$actionPerformed$0(ContentPanel.java:1708)
com.spotifyxp.swingextension.ContextMenu.lambda$addItem$3(ContextMenu.java:80)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.AbstractButton.doClick(AbstractButton.java:376)
javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
java.awt.Component.processMouseEvent(Component.java:6539)
javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
java.awt.Container.processEvent(Container.java:2239)
java.awt.Component.dispatchEventImpl(Component.java:4889)
java.awt.Container.dispatchEventImpl(Container.java:2297)
java.awt.Component.dispatchEvent(Component.java:4711)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
java.awt.Container.dispatchEventImpl(Container.java:2283)
java.awt.Window.dispatchEventImpl(Window.java:2746)
java.awt.Component.dispatchEvent(Component.java:4711)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
java.awt.EventQueue$4.run(EventQueue.java:733)
java.awt.EventQueue$4.run(EventQueue.java:731)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by werwolf2303** [comment]
Select and right click on the row you want to copy I am using getSelectedRow() and it throws an exception if nothing was selected

**Comment by lesar8** [comment]
I already did it, but a lot of times it doesn't work when some random logs copied instead of what I select. The rare times when it copied the correct line, it then inserts many random log lines sequentially.

**Comment by werwolf2303** [comment]
thats weird I will look into that when I am done eating

**Comment by werwolf2303** [comment]
This is very weird I will look further into that tomorrow
