### ISSUE TITLE
Stuck on "Creating CanvasPlayer...."

### ISSUE THREAD

**Issue by VovDev1434** [SpotifyXP/SpotifyXP#8]
Hello! I found about your project recently and had problems with actually making it to work. After logging in to my second spotify account, the loading process stucks on the "Creating CanvasPlayer...." Stage. I even tried using it on windows 7 - same thing. Is there a way to fix it?

**Comment by werwolf2303** [comment]
Please run this with cmd in the folder were SpotifyXP.jar is: "java -jar SpotifyXP.jar --setup-complete --debug"

**Comment by werwolf2303** [comment]
Please send me what that outputs

**Comment by VovDev1434** [comment]
Hello again and thanks for giving in! I guess that issues have started from these code lines, so there you go.

SpotifyXP [INFO ] Building ContentPanel
Module [DEBUG ] Update volume. {volume: 65536/65536}}
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get height for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get width for image
SpotifyXP [WARNING ] [HomeTab] Couldnt get name of section
Module [INFO ] Put state. {ts: 1701427020890, connId: NTY4O...BOEQ2, reason: VOL
UME_CHANGED, request: device { device_info { can_play: true volume: 65536 name:
"SpotifyXP" capabilities { can_be_player: true gaia_eq_connect_id: true supports
_logout: true is_observable: true volume_steps: 64 supported_types: "audio/episo
de" supported_types: "audio/track" command_acks: true supports_playlist_v2: true
 is_controllable: true supports_transfer_command: true supports_command_request:
 true supports_gzip_pushes: true } device_software_version: "librespot-java ?.?.
?" device_type: COMPUTER spirc_version: "3.2.6" device_id: "5689b29db23d97215e15
4ac4621c0e092f6df08b" client_id: "65b708073fc0480ea92a077233ca87bd" } player_sta
te { context_restrictions { } playback_speed: 1.0 position_as_of_timestamp: 0 is
_system_initiated: true options { shuffling_context: false repeating_context: fa
lse repeating_track: false } suppressions { } } } member_type: CONNECT_STATE put
_state_reason: VOLUME_CHANGED has_been_playing_for_ms: 0 client_side_timestamp:
1701427020890}}
SpotifyXP [THROWABLE ] com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:
302)
SpotifyXP [THROWABLE ] com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:
455)
SpotifyXP [THROWABLE ] com.sun.jna.Native.register(Native.java:1716)
SpotifyXP [THROWABLE ] com.sun.jna.Native.register(Native.java:1437)
SpotifyXP [THROWABLE ] uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:98
)
SpotifyXP [THROWABLE ] uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(L
ibVlcVersion.java:49)
SpotifyXP [THROWABLE ] uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersio
n(MediaPlayerFactory.java:206)
SpotifyXP [THROWABLE ] uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNat
iveLibrary(MediaPlayerFactory.java:192)
SpotifyXP [THROWABLE ] uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(Medi
aPlayerFactory.java:119)
SpotifyXP [THROWABLE ] uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(Medi
aPlayerFactory.java:174)
SpotifyXP [THROWABLE ] com.spotifyxp.video.CanvasPlayer.<init>(CanvasPlayer.java
:57)
SpotifyXP [THROWABLE ] com.spotifyxp.panels.ContentPanel.<init>(ContentPanel.jav
a:2601)
SpotifyXP [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:275)
java.lang.UnsatisfiedLinkError: Unable to load library 'libvlc':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86/libvlc.dll) not found in resource path ([file:/C:/Docu
ments%20and%20Settings/Administrator/Desktop/SpotifyXP.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
        at com.sun.jna.Native.register(Native.java:1716)
        at com.sun.jna.Native.register(Native.java:1437)
        at uk.co.caprica.vlcj.binding.LibVlc.<clinit>(LibVlc.java:98)
        at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion
.java:49)
        at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlaye
rFactory.java:206)
        at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(M
ediaPlayerFactory.java:192)
        at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFacto
ry.java:119)
        at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFacto
ry.java:174)
        at com.spotifyxp.video.CanvasPlayer.<init>(CanvasPlayer.java:57)
        at com.spotifyxp.panels.ContentPanel.<init>(ContentPanel.java:2601)
        at com.spotifyxp.Initiator.main(Initiator.java:275)
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could n
ot be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)

                ... 12 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could n
ot be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)

                ... 12 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could n
ot be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:265)

                ... 12 more
        Suppressed: java.io.IOException: Native library (win32-x86/libvlc.dll) n
ot found in resource path ([file:/C:/Documents%20and%20Settings/Administrator/De
sktop/SpotifyXP.jar])
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)

                ... 12 more

**Comment by werwolf2303** [comment]
Can you try a nightly version

**Comment by VovDev1434** [comment]
sure, but, where can it be downloaded? can you please send me a link or something?

**Comment by werwolf2303** [comment]
Its under the Actions tab in the Repository

**Comment by Snaky1a** [comment]
@VovDev1434, you will need to install VLC 3.0.20 and it works
![image](https://github.com/SpotifyXP/SpotifyXP/assets/131266173/9448117e-b0fc-4282-b2f8-2a6eec36c660)

**Comment by VovDev1434** [comment]
thank you so much! it worked! have a nice day, bro :)
