### ISSUE TITLE
Cannot launch installer

### ISSUE THREAD

**Issue by benji2341** [SpotifyXP/SpotifyXP#9]
When i try to launch the .jar file i get a  "Java Virtual Machine Launcher" error saying: "A Java Exception has occurred"

I am using a Samsung NC10 with Windows XP Professional SP3 and Java V7 Update 76

**Comment by Snaky1a** [comment]
> I am using a Samsung NC10 with Windows XP Professional SP3 and Java V7 Update 76

Have you tried on Java 8?

**Comment by werwolf2303** [comment]
Java 8 is required. Java 7 is possible but not without help

**Comment by benji2341** [comment]
I can't get java 8 to install. It's hard to try the versions as you need a oracle account and it wont let me get one, any suggestions.
Sorry for the late reply, I've been busy.

**Comment by werwolf2303** [comment]
I can host a working java setup exe on my server for you to download. If you want

**Comment by benji2341** [comment]
I'm trying the Java 8 Update 73 .msi
https://sourceforge.net/projects/javaclientmsiinstallers/files/Java%208%20Update%2073/
getting my NC10 out so lets hope it works

**Comment by werwolf2303** [comment]
https://archive.org/download/jre-8u152-windows-i586/jre-8u152-windows-i586.exe

**Comment by benji2341** [comment]
So that didn't work, could you host the installer?

**Comment by benji2341** [comment]
What?![IMG20231212123719.jpg](https://github.com/SpotifyXP/SpotifyXP/assets/152732579/891864b9-87b6-4e9a-bfd1-5d313a9ea238)
It says I can install but how?

**Comment by werwolf2303** [comment]
Just press "Ok" it should work

**Comment by werwolf2303** [comment]
Java 8 152 is the last version where the installer works you can get a newer java version but that requires manual installation

**Comment by benji2341** [comment]
Hey it worked![IMG20231212124554.jpg](https://github.com/SpotifyXP/SpotifyXP/assets/152732579/39c5338c-270c-47e1-a2aa-affd9ff40125)

**Comment by werwolf2303** [comment]
You're welcome
